version: '3'
services:
  redis:
    #image: redis:7.4.1
    image: redis/redis-stack-server:7.4.0-v1
    container_name: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
      - ./ssl:/usr/local/etc/redis/ssl
    ports:
      - 6379:6379
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G # Limit memory for container 512 MB
          cpus: "2.0" # Limit CPU for container is 0.5 (~50% of single core)
