version: '3'
services:
  redis:
    #image: redis:7.4.1
    image: redis/redis-stack-server:7.4.0-v1
    container_name: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
      - ./ssl:/usr/local/etc/redis/ssl
    ports:
      - 6379:6379
    restart: always
